# run
fortran: fortran_compile fortran_run
# compile fortran
fortran_compile:
	gfortran -Wall logs.f95
# fun fortran
fortran_run:
	./a.out

# github
git: git_add git_commit git_push

git_add:
	git add -A

git_commit:
	git commit -m "[AUTO]"

git_push:
	git push